services:
  - type: web
    name: finance-app
    env: node
    buildCommand: |
      apt-get update && apt-get install -y python3.9 python3-pip
      python3.9 -m pip install -r requirements.txt
      npm install
    startCommand: npm start
    envVars:
      - key: PYTHON_VERSION
        value: "3.9"
